arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ nc -lvnp 9001                                                  
listening on [any] 9001 ...                               
^C                          
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                    
Traceback (most recent call last):                       
  File "rsa_bruteforce.py", line 19, in <module>         
    f = open('rsa_in')      
IOError: [Errno 2] No such file or directory: 'rsa_in'   
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                    
Traceback (most recent call last):                       
  File "rsa_bruteforce.py", line 23, in <module>         
    for line in f:          
NameError: name 'f' is not defined                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                    
Traceback (most recent call last):                       
  File "rsa_bruteforce.py", line 23, in <module>         
    for line in g:          
NameError: name 'g' is not defined                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                              
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                    
Traceback (most recent call last):                       
  File "rsa_bruteforce.py", line 30, in <module>         
    key = RSA.construct((x,e,d,prime1,prime2))           
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 539, in construct                         
    key = self._math.rsa_construct(*tup)                 
TypeError: argument 1 must be long, not None             
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                    
decrypted flag is 0x3665666331613564626238393034373531636536353636613330356262386566L                             
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim rsa_bruteforce.py                                       
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ cat debug.txt                                                  
7493025776465062819629921475535241674460826792785520881387158343265274170009282504884941039852933109163193651830303308312565580445669284847225535166520307                                                                                 
7020854527787566735458858381555452648322845008266612906844847937070333480373963284146649074252278753696897245898433245929775591091774274652021374143174079                                                                                 
30802007917952508422792869021689193927485016332713622527025219105154254472344627284947779726280995431947454292782426313255523137610532323813714483639434257536830062768286377920010841850346837238015571464755074669373110411870331706974573498912126641409821855678581804467608824177508976254759319210955977053997                                            
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim debug                                                                                                                                                                            
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim debug.txt                                                                                                                                                                        
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ vim output.txt                                                 
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ cat output.txt                                                 
44641914821074071930297814589851746700593470770417111804648920018396305246956127337150936081144106405284134845851392541080862652386840869768622438038690803472550278042463029816028777378141217023336710545449512973950591755053735796799773369044083673911035030605581144977552865771395578778515514288930832915182                                            
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$ python rsa_bruteforce.py                                       
decrypted flag is 0x3665666331613564626238393034373531636536353636613330356262386566L                                
arjun@broly:~/Documents/HacktheBox/retired/brainfuck$     
